tap "buo/cask-upgrade"
tap "cloudflare/cloudflare"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "nicoverbruggen/cask"
brew "act"
brew "libpng", link: false
brew "webp"
brew "openssl@1.1"
brew "asciinema"
brew "aspell"
brew "python@3.9"
brew "awscli"
brew "bash"
brew "boost"
brew "gettext"
brew "pkg-config"
brew "cocoapods"
brew "gd"
brew "php", restart_service: true, link: false
brew "composer"
brew "cowsay"
brew "dark-mode"
brew "dnsmasq", restart_service: true
brew "doctl"
brew "ffmpeg"
brew "fswatch"
brew "fzf"
brew "geoip"
brew "geoipupdate"
brew "gh"
brew "gifsicle"
brew "gifski"
brew "git"
brew "git-extras"
brew "git-flow"
brew "git-lfs"
brew "git-quick-stats"
brew "gnu-sed"
brew "gnu-tar"
brew "pinentry"
brew "gnupg"
brew "go"
brew "htop"
brew "httrack"
brew "hub"
brew "hugo"
brew "imagemagick"
brew "iperf"
brew "iperf3"
brew "jq"
brew "lazydocker"
brew "libpsl"
brew "libxml2"
brew "lynx"
brew "mackup"
brew "mas"
brew "megatools"
brew "mysql", restart_service: true
brew "nginx", restart_service: true
brew "php@7.4", restart_service: true
brew "php@8.0", restart_service: true, link: true
brew "pinentry-mac"
brew "poppler"
brew "rclone"
brew "redis", restart_service: true
brew "ripgrep"
brew "rsync"
brew "s3cmd"
brew "slowhttptest"
brew "smartmontools"
brew "terraform"
brew "tesseract-lang"
brew "travis"
brew "tree"
brew "vim"
brew "wget"
brew "youtube-dl"
brew "zsh"
brew "zsh-completions"
brew "zsh-syntax-highlighting"
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "appcleaner"
cask "balenaetcher"
cask "bartender"
cask "betterzip"
cask "box-sync"
cask "camo-studio"
cask "chromedriver"
cask "docker"
cask "dropshare"
cask "figma"
cask "flutter"
cask "font-jetbrains-mono"
cask "google-chrome"
cask "imageoptim"
cask "iterm2"
cask "logitech-options"
cask "moonlight"
cask "ngrok"
cask "paw"
cask "phpmon"
cask "plex"
cask "postman"
cask "qlcolorcode"
cask "qlimagesize"
cask "qlprettypatch"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "rectangle"
cask "slack"
cask "spotify"
cask "tableplus"
cask "teamviewer"
cask "telegram"
cask "timemachineeditor"
cask "transmit"
cask "viscosity"
cask "visual-studio-code"
cask "vlc"
cask "vmware-fusion"
cask "webpquicklook"
cask "whatsapp"
cask "zoom"
mas "1Blocker", id: 1365531024
mas "Affinity Designer", id: 824171161
mas "Animatrice", id: 1133146803
mas "DaisyDisk", id: 411643860
mas "Dato", id: 1470584107
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "iStat Menus", id: 1319778037
mas "Keynote", id: 409183694
mas "Microsoft Excel", id: 462058435
mas "Microsoft PowerPoint", id: 462062816
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft Word", id: 462054704
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Parcel", id: 639968404
mas "Patterns", id: 429449079
mas "Pocket", id: 568494494
mas "Super Agent", id: 1568262835
mas "The Unarchiver", id: 425424353
mas "Twitter", id: 1482454543
